name: Release MSIX Prod

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-prod:
    uses: ./.github/workflows/release-msix-common.yml
    with:
      channel: prod
      prerelease: false
    secrets: inherit
